### ISSUE TITLE
Add docusaurus template generator to Fresh App Factory.

### ISSUE THREAD

**Issue by dtinth** [fresh-app/factory#7]
## Background

[Fresh App Factory](https://fresh-app.github.io/) is a project that automatically generate template repositories for popular web frameworks.

[Docusaurus](https://docusaurus.io/) is a popular documentation generator.

## Task

- Create a generator `fresh-docusaurus-site` that [generates a Docusaurus website](https://docusaurus.io/docs/installation) using `create-docusaurus`.
    - [Use the classic template with TypeScript.](https://docusaurus.io/docs/installation#:~:text=You%20can%20also%20use%20the%20template%27s%20TypeScript%20variant%20by%20passing%20the%20%2D%2Dtypescript%20flag.%20See%20TypeScript%20support%20for%20more%20information.)
    - Check out other generator files
- To work on this task you need to be using Linux, macOS (Intel-based), or WSL. Please use Node.js v16 and also install Docker on your system. Please note that this project is only tested on Linux and it might not work on Windows or macOS. However, you can use [Gitpod](https://gitpod.io/workspaces) to develop on the cloud. The set instructions below are confirmed to be working on Gitpod.
- Your PR should add a single file, `src/generators/fresh-docusaurus-site.ts`.
- Please include the generated screenshot (see below) in your PR to confirm that it is working.

## How to develop

1. Clone the repository.
2. Install dependencies
    ```
    yarn
    ```
3. Build a Docker image
    ```
    bin/build
    ```
4. **Only on Gitpod**: Temporarily edit `bin/runner` and remove the 7th line that says `--ipc=host \`. Do not commit this file.
5. Try running an existing generator
    ```
    bin/run fresh-vite-app-react
    ```
    When run, you will get these files:
    - `workspace/fresh-app` - Output project
    - `workspace/tmp/screenshot.png` - Browser screenshot
6. Create your generator file and test it using with `bin/run fresh-docusaurus-site`.

## Hacktoberfest

If you would like to work on this task, please write a comment stating your intent. We will then assign the issue to you. To ensure continuity, the issue will be unassigned after 3 days of inactivity — so please keep us updated.

If you encounter any problem, please include relevant logs and screenshot so it’s easy to troubleshoot.

**Comment by gavinroderick** [comment]
hey there, I'd be keen to pick this up!

**Comment by dtinth** [comment]
@gavinroderick Thanks, please go ahead! 😄

**Comment by gavinroderick** [comment]
have opened up a PR - hope it's ok! If so, would you be able to add the `hacktoberfest-accepted` label? :)

**Comment by dtinth** [comment]
@gavinroderick Your PR #8 has been merged, this should count on your Hacktoberfest dashboard now.

**Comment by gavinroderick** [comment]
Nice! Thanks for taking part, this is my first hacktoberfest, I appreciate it! 💃
